# escape=`

ARG RUNTIME_IMAGE=mcr.microsoft.com/windows/nanoserver@sha256:87af42244113104b3ce4b5646f9ec1ab6690e6753dd68924e698bdc2132546b3
FROM ${RUNTIME_IMAGE}
USER ContainerUser
WORKDIR C:/workspace
COPY release/windows/amd64/qtest-publisher.exe C:/bin/qtest-publisher.exe
ENV PATH="C:\bin;C:\Windows\system32;C:\Windows"
LABEL org.opencontainers.image.source="https://github.com/DevanshMathur19/qtest-publisher" `
      org.opencontainers.image.revision="803c1f8de400c272a4a81395c8906bebaa6e1e84" `
      org.opencontainers.image.version="1.0.1" `
      io.harness.windows.build="20348" `
      io.harness.release.status="candidate"
ENTRYPOINT ["qtest-publisher"]
