# escape=`

ARG RUNTIME_IMAGE=mcr.microsoft.com/windows/nanoserver@sha256:c5980a8cd05a3902130f95fbad5b7db35d21e00183b063ee6bca5c1dcab40ce9
FROM ${RUNTIME_IMAGE}
USER ContainerAdministrator
WORKDIR C:/workspace
COPY release/windows/amd64/qtest-publisher.exe C:/bin/qtest-publisher.exe
LABEL org.opencontainers.image.source="https://git.harness.io/gCoPSwHxS7ipOgx2iA9tOQ/default/Drone_Plugins/qtest-publisher" `
      org.opencontainers.image.revision="0f732e8585cd7f338f4cd39b9e5defa32723d6d2" `
      org.opencontainers.image.version="1.0.0" `
      io.harness.windows.build="17763" `
      io.harness.release.status="candidate"
ENTRYPOINT ["C:\\bin\\qtest-publisher.exe"]
