ARG RUNTIME_IMAGE=gcr.io/distroless/static-debian12@sha256:06c3c14b7fa252d9f4285242d2d665ce3b51f74b02d3c529464f220f2912aecb
FROM ${RUNTIME_IMAGE}
COPY --chown=65532:65532 release/linux/arm64/qtest-publisher /qtest-publisher
LABEL org.opencontainers.image.source="https://github.com/harness-community/qtest-publisher" \
      org.opencontainers.image.revision="8e48fef728a860ad18f0522b83b75938dad0cae3" \
      org.opencontainers.image.version="1.0.0" \
      io.harness.release.status="candidate"
USER 65532:65532
ENTRYPOINT ["/qtest-publisher"]
