# escape=`

ARG RUNTIME_IMAGE=mcr.microsoft.com/windows/nanoserver@sha256:4fe6f59e0aadb628a933345eae1f5ab43a2af802969ac0e2ef996c66a3188438
FROM ${RUNTIME_IMAGE}
USER ContainerUser
WORKDIR C:/workspace
COPY release/windows/amd64/qtest-publisher.exe C:/bin/qtest-publisher.exe
ENV PATH="C:\bin;C:\Windows\system32;C:\Windows"
LABEL org.opencontainers.image.source="https://github.com/DevanshMathur19/qtest-publisher" `
      org.opencontainers.image.revision="803c1f8de400c272a4a81395c8906bebaa6e1e84" `
      org.opencontainers.image.version="1.0.1" `
      io.harness.windows.build="26100" `
      io.harness.release.status="candidate"
ENTRYPOINT ["qtest-publisher"]
