ARG RUNTIME_IMAGE=gcr.io/distroless/static-debian12@sha256:52dcfbabb7457ea47c82f6e13af8c8a4a1d9f7b0145142b3ecab20f2b888411d
FROM ${RUNTIME_IMAGE}
COPY --chown=65532:65532 release/linux/amd64/qtest-publisher /qtest-publisher
LABEL org.opencontainers.image.source="https://git.harness.io/gCoPSwHxS7ipOgx2iA9tOQ/default/Drone_Plugins/qtest-publisher" \
      org.opencontainers.image.revision="0f732e8585cd7f338f4cd39b9e5defa32723d6d2" \
      org.opencontainers.image.version="1.0.0" \
      io.harness.release.status="candidate"
USER 65532:65532
ENTRYPOINT ["/qtest-publisher"]
